INSERT INTO users (user_name, first_name, last_name, email, password, phone, user_role, picture) VALUES
('soren9','Soren','Burnett','soren@burnett.com','password','875282077','guest','picture'),
('freya1','Freya','Lucas','freya@lucas.com','password','766670340','guest','picture'),
('isabella6','Isabella','Shaw','isabella@shaw.com','password','483744977','ghost','picture'),
('arlo3','Arlo','Burke','arlo@burke.com','password','20088219','host','picture'),
('ivy5','Ivy','Mcgee','ivy@mcgee.com','password','511120414','host','picture'),
('adeline9','Adeline','Medina','adeline@medina.com','password','137283270','admin','picture'),
('maisie1','Maisie','Howard','maisie@howard.com','password','650324540','admin','picture'),
('rose10','Rose','Burke','rose@burke.com','password','875707806','admin','picture'),
('elijah7','Elijah','Clayton','elijah@clayton.com','password','71044804','admin','picture'),
('chloe1','Chloe','Trujillo','chloe@trujillo.com','password','172339763','host','picture');


INSERT INTO listings (listing_title,listing_description,cost,property_type,listing_location,rating,picture) VALUES
('Luxury Beach House Perfect for Romantic Weekend Getaway','Tri-tip venison shank chislic andouille, pancetta jerky tongue swine salami strip steak shoulder. Pork boudin burgdoggen, pork belly rump shoulder venison ham. Capicola fatback pork belly pancetta. Spare ribs salami pork pastrami drumstick turkey. Capicola jowl porchetta, ham hock shankle kielbasa tri-tip pancetta chislic chicken. Andouille corned beef buffalo turkey landjaeger doner alcatra flank tongue.','106','Villa','Ukraine','13','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Enjoy Sunsets at Fully Equipped 2BR Condo at the Beach','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','102','Apartment','Dominican Republic','12','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Rustic Loft w/ Breakfast + Gym','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','107','House','Iran','11','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Charming Chalet w/ a Washer + Gym','Cupim pork chop pork belly frankfurter leberkas. Shank landjaeger pork belly porchetta jowl picanha kielbasa buffalo ball tip jerky swine tongue hamburger tail. Buffalo doner tenderloin chuck filet mignon, bacon pork chop chicken fatback. Turkey tenderloin shoulder beef, capicola buffalo tail.','102','House','Libya','8','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','Ribeye ham hock doner bacon. Cupim salami hamburger chislic. Pig pastrami turducken tail t-bone beef ribs biltong kielbasa landjaeger. Pig short loin shank biltong pork belly filet mignon turkey pancetta prosciutto bacon rump ground round ball tip salami. Beef ribs pork belly picanha, chuck kevin pork tri-tip boudin beef ball tip bacon ground round bresaola short ribs chislic. Flank turducken kielbasa, andouille jowl pork turkey cupim alcatra pork chop shank.','101','Apartment','Cuba','5','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Enjoy Sunsets at Fully Equipped 2BR Condo at the Beach','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','105','Bed and Breakfast','Dominican Republic','6','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','105','Bed and Breakfast','Cyprus','11','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','Cupim pork chop pork belly frankfurter leberkas. Shank landjaeger pork belly porchetta jowl picanha kielbasa buffalo ball tip jerky swine tongue hamburger tail. Buffalo doner tenderloin chuck filet mignon, bacon pork chop chicken fatback. Turkey tenderloin shoulder beef, capicola buffalo tail.','109','Villa','Vietnam','11','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Enjoy Sunsets at Fully Equipped 2BR Condo at the Beach','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','109','House','Nicaragua','12','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Rustic Loft w/ Breakfast + Gym','Tri-tip venison shank chislic andouille, pancetta jerky tongue swine salami strip steak shoulder. Pork boudin burgdoggen, pork belly rump shoulder venison ham. Capicola fatback pork belly pancetta. Spare ribs salami pork pastrami drumstick turkey. Capicola jowl porchetta, ham hock shankle kielbasa tri-tip pancetta chislic chicken. Andouille corned beef buffalo turkey landjaeger doner alcatra flank tongue.','106','Bed and Breakfast','Brazil','13','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg');
