INSERT INTO users (user_name, first_name, last_name, email, password, phone, user_role, picture) VALUES
('kai8','Kai','Fleming','kai@fleming.com','$2a$10$2utI9V7eOn8I1lC584fdK.C1n5WpQ6C4/GodaLScq26g/TsPKH4F6','277864467','ghost','picture'),
('aria7','Aria','Salazar','aria@salazar.com','$2a$10$IuMglZNqZqX6A10u/KNr2udjRaW05Qi8U3DAtif3TrLI3IL7G1bBK','827481691','host','picture'),
('aria6','Aria','Shaw','aria@shaw.com','$2a$10$0EV4qGVlxX3zj3bO1.QdlOu8Zdnbpnazv1Ajn1CX.MLbNMu.8urXS','532563554','host','picture'),
('caleb6','Caleb','Horn','caleb@horn.com','$2a$10$oUm29uz3Ay2psT.R1sUGROZ92A6nxH5ZirmRGECVeQ09DPQhRKAsm','869962191','guest','picture'),
('leo5','Leo','House','leo@house.com','$2a$10$DUSAbeXnFbsgbCrQQWLwA.TbayVf6gO54Y5YaOJEgDJsxZTid3rlK','600278022','admin','picture'),
('john3','John','Horn','john@horn.com','$2a$10$jKlRuJbDH30Cwx48V1PNXOlOK9c6KAeiUFdTP6yjhf8EIPGduvL5O','604768779','admin','picture'),
('mia1','Mia','Fritz','mia@fritz.com','$2a$10$NoWdjQiwu6x8ZIuPB.UHpufK8i3AwIdsfHkpxYC8KJNtkWH8g95gq','548111930','host','picture'),
('cassius4','Cassius','Orozco','cassius@orozco.com','$2a$10$RWTdI0pV0aHb7SVZCnBoQO8Hkwsfe96JwkXL09E65NiI4YMjpKRfq','571545266','guest','picture'),
('charlotte10','Charlotte','Orozco','charlotte@orozco.com','$2a$10$oAgSzFi5GJnoNSbVvS2moO2eXcoyXm1ZH9w5PuEfr3DW.tHesTcKO','840126859','host','picture'),
('violet3','Violet','Fritz','violet@fritz.com','$2a$10$dQCCpfEs9nCiKaxcbZEidujL4E2qQ2AF18cdmKfpMrNi1jcwU3FOa','772644646','admin','picture');


INSERT INTO listings (listing_title,listing_description,cost,property_type,listing_location,rating,picture) VALUES
('Rustic Loft w/ Breakfast + Gym','Tri-tip venison shank chislic andouille, pancetta jerky tongue swine salami strip steak shoulder. Pork boudin burgdoggen, pork belly rump shoulder venison ham. Capicola fatback pork belly pancetta. Spare ribs salami pork pastrami drumstick turkey. Capicola jowl porchetta, ham hock shankle kielbasa tri-tip pancetta chislic chicken. Andouille corned beef buffalo turkey landjaeger doner alcatra flank tongue.','100','Apartment','Congo, Democratic Republic of the','5','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Rustic Loft w/ Breakfast + Gym','Ribeye ham hock doner bacon. Cupim salami hamburger chislic. Pig pastrami turducken tail t-bone beef ribs biltong kielbasa landjaeger. Pig short loin shank biltong pork belly filet mignon turkey pancetta prosciutto bacon rump ground round ball tip salami. Beef ribs pork belly picanha, chuck kevin pork tri-tip boudin beef ball tip bacon ground round bresaola short ribs chislic. Flank turducken kielbasa, andouille jowl pork turkey cupim alcatra pork chop shank.','101','Hostel','Syria','7','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','Tri-tip venison shank chislic andouille, pancetta jerky tongue swine salami strip steak shoulder. Pork boudin burgdoggen, pork belly rump shoulder venison ham. Capicola fatback pork belly pancetta. Spare ribs salami pork pastrami drumstick turkey. Capicola jowl porchetta, ham hock shankle kielbasa tri-tip pancetta chislic chicken. Andouille corned beef buffalo turkey landjaeger doner alcatra flank tongue.','104','House','Ethiopia','8','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','103','Bed and Breakfast','Germany','5','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','T-bone filet mignon short ribs leberkas. Sirloin flank spare ribs landjaeger biltong kevin shankle pork loin. Tail doner ham hock andouille short ribs meatball. Kielbasa pork loin frankfurter landjaeger burgdoggen ground round prosciutto, andouille shank swine cupim drumstick tenderloin porchetta meatloaf.','101','Apartment','Kyrgyzstan','14','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','T-bone filet mignon short ribs leberkas. Sirloin flank spare ribs landjaeger biltong kevin shankle pork loin. Tail doner ham hock andouille short ribs meatball. Kielbasa pork loin frankfurter landjaeger burgdoggen ground round prosciutto, andouille shank swine cupim drumstick tenderloin porchetta meatloaf.','108','House','Belgium','9','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Enjoy Sunsets at Fully Equipped 2BR Condo at the Beach','Ribeye ham hock doner bacon. Cupim salami hamburger chislic. Pig pastrami turducken tail t-bone beef ribs biltong kielbasa landjaeger. Pig short loin shank biltong pork belly filet mignon turkey pancetta prosciutto bacon rump ground round ball tip salami. Beef ribs pork belly picanha, chuck kevin pork tri-tip boudin beef ball tip bacon ground round bresaola short ribs chislic. Flank turducken kielbasa, andouille jowl pork turkey cupim alcatra pork chop shank.','103','Villa','Kazakhstan','7','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Rustic Loft w/ Breakfast + Gym','Tri-tip venison shank chislic andouille, pancetta jerky tongue swine salami strip steak shoulder. Pork boudin burgdoggen, pork belly rump shoulder venison ham. Capicola fatback pork belly pancetta. Spare ribs salami pork pastrami drumstick turkey. Capicola jowl porchetta, ham hock shankle kielbasa tri-tip pancetta chislic chicken. Andouille corned beef buffalo turkey landjaeger doner alcatra flank tongue.','105','Apartment','Luxembourg','12','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','Cupim pork chop pork belly frankfurter leberkas. Shank landjaeger pork belly porchetta jowl picanha kielbasa buffalo ball tip jerky swine tongue hamburger tail. Buffalo doner tenderloin chuck filet mignon, bacon pork chop chicken fatback. Turkey tenderloin shoulder beef, capicola buffalo tail.','106','Villa','Paraguay','6','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','Ribeye ham hock doner bacon. Cupim salami hamburger chislic. Pig pastrami turducken tail t-bone beef ribs biltong kielbasa landjaeger. Pig short loin shank biltong pork belly filet mignon turkey pancetta prosciutto bacon rump ground round ball tip salami. Beef ribs pork belly picanha, chuck kevin pork tri-tip boudin beef ball tip bacon ground round bresaola short ribs chislic. Flank turducken kielbasa, andouille jowl pork turkey cupim alcatra pork chop shank.','106','Apartment','Slovakia','5','https://media-cdn.tripadvisor.com/media/vr-splice-j/05/a0/88/17.jpg');
