INSERT INTO users (user_name, first_name, last_name, email, password, phone, user_role, picture) VALUES
('imogen7','Imogen','Neal','imogen@neal.com','password','932970106','admin','picture'),
('hazel5','Hazel','Chaney','hazel@chaney.com','password','879596216','host','picture'),
('maeve3','Maeve','Chaney','maeve@chaney.com','password','596639483','host','picture'),
('mia7','Mia','Cline','mia@cline.com','password','223960330','ghost','picture'),
('caleb4','Caleb','Clarke','caleb@clarke.com','password','941252561','ghost','picture'),
('jayden5','Jayden','Ward','jayden@ward.com','password','484129588','host','picture'),
('eleanor4','Eleanor','Goodwin','eleanor@goodwin.com','password','872587182','guest','picture'),
('finn8','Finn','Fritz','finn@fritz.com','password','363599057','host','picture'),
('isla9','Isla','Hooper','isla@hooper.com','password','194803206','host','picture'),
('violet3','Violet','Trujillo','violet@trujillo.com','password','799307740','host','picture');


INSERT INTO listings (listing_title,listing_description,cost,property_type,listing_location,rating,is_available,picture) VALUES
('Luxury Beach House Perfect for Romantic Weekend Getaway','Cupim pork chop pork belly frankfurter leberkas. Shank landjaeger pork belly porchetta jowl picanha kielbasa buffalo ball tip jerky swine tongue hamburger tail. Buffalo doner tenderloin chuck filet mignon, bacon pork chop chicken fatback. Turkey tenderloin shoulder beef, capicola buffalo tail.','107','Hostel','Slovakia','14','yes','picture of listing'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','100','Hotel','Czech Republic','10','yes','picture of listing'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','Ribeye ham hock doner bacon. Cupim salami hamburger chislic. Pig pastrami turducken tail t-bone beef ribs biltong kielbasa landjaeger. Pig short loin shank biltong pork belly filet mignon turkey pancetta prosciutto bacon rump ground round ball tip salami. Beef ribs pork belly picanha, chuck kevin pork tri-tip boudin beef ball tip bacon ground round bresaola short ribs chislic. Flank turducken kielbasa, andouille jowl pork turkey cupim alcatra pork chop shank.','106','Apartment','Iceland','12','yes','picture of listing'),
('Charming Chalet w/ a Washer + Gym','T-bone filet mignon short ribs leberkas. Sirloin flank spare ribs landjaeger biltong kevin shankle pork loin. Tail doner ham hock andouille short ribs meatball. Kielbasa pork loin frankfurter landjaeger burgdoggen ground round prosciutto, andouille shank swine cupim drumstick tenderloin porchetta meatloaf.','101','Apartment','Bahrain','5','no','picture of listing'),
('Rustic Loft w/ Breakfast + Gym','Tri-tip venison shank chislic andouille, pancetta jerky tongue swine salami strip steak shoulder. Pork boudin burgdoggen, pork belly rump shoulder venison ham. Capicola fatback pork belly pancetta. Spare ribs salami pork pastrami drumstick turkey. Capicola jowl porchetta, ham hock shankle kielbasa tri-tip pancetta chislic chicken. Andouille corned beef buffalo turkey landjaeger doner alcatra flank tongue.','100','Bed and Breakfast','Croatia','8','yes','picture of listing'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','Cupim pork chop pork belly frankfurter leberkas. Shank landjaeger pork belly porchetta jowl picanha kielbasa buffalo ball tip jerky swine tongue hamburger tail. Buffalo doner tenderloin chuck filet mignon, bacon pork chop chicken fatback. Turkey tenderloin shoulder beef, capicola buffalo tail.','100','Bed and Breakfast','Australia','10','yes','picture of listing'),
('Rustic Private Cottage w/ King Bed + Oceanside View','Ribeye ham hock doner bacon. Cupim salami hamburger chislic. Pig pastrami turducken tail t-bone beef ribs biltong kielbasa landjaeger. Pig short loin shank biltong pork belly filet mignon turkey pancetta prosciutto bacon rump ground round ball tip salami. Beef ribs pork belly picanha, chuck kevin pork tri-tip boudin beef ball tip bacon ground round bresaola short ribs chislic. Flank turducken kielbasa, andouille jowl pork turkey cupim alcatra pork chop shank.','106','House','Tunisia','7','no','picture of listing'),
('Rustic Private Cottage w/ King Bed + Oceanside View','Bacon ipsum dolor amet pork loin shoulder beef, brisket ham bacon meatloaf. Ground round swine shoulder tail pastrami, buffalo venison meatball corned beef hamburger beef pork strip steak. Burgdoggen tail biltong turducken, kevin chicken beef ribs cow. Landjaeger cow pig ground round bresaola, beef ribs prosciutto cupim flank kevin jowl bacon boudin tail spare ribs.','105','House','Bangladesh','6','no','picture of listing'),
('Luxury Beach House Perfect for Romantic Weekend Getaway','T-bone filet mignon short ribs leberkas. Sirloin flank spare ribs landjaeger biltong kevin shankle pork loin. Tail doner ham hock andouille short ribs meatball. Kielbasa pork loin frankfurter landjaeger burgdoggen ground round prosciutto, andouille shank swine cupim drumstick tenderloin porchetta meatloaf.','109','Hostel','Trinidad and Tobago','10','yes','picture of listing'),
('Spacious 4 BR Near Eiffel Tour – 7 Min Walk','Cupim pork chop pork belly frankfurter leberkas. Shank landjaeger pork belly porchetta jowl picanha kielbasa buffalo ball tip jerky swine tongue hamburger tail. Buffalo doner tenderloin chuck filet mignon, bacon pork chop chicken fatback. Turkey tenderloin shoulder beef, capicola buffalo tail.','106','House','Fiji','10','no','picture of listing');
